<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [25]:
from planetarypy import utils

In [26]:
utils.nasa_datetime_to_iso('2016-366T23:11:10.618')

'2016-12-31T23:11:10.618000'

In [27]:
import spicer

In [28]:
from numpy.linalg import norm

from astropy import units as u

In [29]:
import spiceypy as spice

In [30]:
spicer.kernels.KERNELROOT

PosixPath('/Users/klay6683/Dropbox/src/spicer/spicer/kernels')

In [31]:
triton = spicer.TritonSpicer(obs='EARTH')

spice.furnsh("/Users/klay6683/Dropbox/SternchenAndMe/SPICE_kernels/spk/nep081.bsp")

print (triton.solar_constant)

print (triton.center_to_sun)

dist = norm(triton.center_to_sun)* u.km

dist.to(u.au)

1.5228368785874833
[-2.26013976e+09  2.63912303e+09 -2.82628792e+09]


<Quantity 29.94001539 AU>

In [32]:
ang = 5 * u.mas
ang

<Quantity 5. mas>

In [52]:
ang = 0.017 * u.arcsec

In [53]:
angval = ang.to(u.rad).value

In [54]:
angval * dist

<Quantity 414.42827194 km>

In [35]:
def calc_resolution_element(ang, dist):
    return np.sin(ang.to(u.rad)/2)*2 * dist

In [36]:
def calc_pixels_imaged(spicer, res_element):
    return spicer.radii[0]*u.km/res_element

In [37]:
res_elem = calc_resolution_element(ang, dist)
res_elem

<Quantity 108.57311609 km>

In [38]:
calc_pixels_imaged(triton, res_elem)

<Quantity 12.45796426>

In [39]:
enc = spicer.EnceladusSpicer(obs='EARTH')

spice.furnsh("/Users/klay6683/Dropbox/SternchenAndMe/SPICE_kernels/spk/sat375.bsp")

print (enc.solar_constant)

print (enc.center_to_sun)

dist = norm(enc.center_to_sun)* u.km

dist.to(u.au)

13.473512983329595
[8.46502522e+08 1.05589126e+09 6.60244847e+08]


<Quantity 10.06556805 AU>

In [40]:
res_elem = calc_resolution_element(ang, dist)
res_elem

<Quantity 36.50132021 km>

In [41]:
calc_pixels_imaged(enc, res_elem)

<Quantity 7.02988272>

In [46]:
pluto = spicer.PlutoSpicer(obs='EARTH')

# spice.furnsh("/Users/klay6683/Dropbox/SternchenAndMe/SPICE_kernels/spk/de432s.bsp")
spice.furnsh("/Users/klay6683/Dropbox/SternchenAndMe/SPICE_kernels/spk/plu055.bsp")

print (pluto.solar_constant)

print (pluto.center_to_sun)

dist = norm(pluto.center_to_sun)* u.km

dist.to(u.au)

1.2082507534084304
[2.86216405e+09 3.86499536e+08 4.11618136e+09]


<Quantity 33.61245043 AU>

In [48]:
res_elem = calc_resolution_element(ang, dist)
res_elem

<Quantity 121.89066822 km>

In [49]:
calc_pixels_imaged(pluto, res_elem)

<Quantity 9.80386782>

In [50]:
pluto.radii

Radii(a=1195.0, b=1195.0, c=1195.0)

In [51]:
triton.radii

Radii(a=1352.6, b=1352.6, c=1352.6)